name: jsonld-checker-api
app: jsonld-checker
component: express
org: gjgdserverless
repo: https://github.com/gjgd/jsonld-checker
license: MIT

inputs:
  src: ./
  domain: api-jsonld-checker.gjgd.xyz
  env:
    TABLE_NAME: ${output:jsonld-checker-db.name}
    # Comment this line before deploying for the first time
    # because the output is created after the first deploy
    API_URL: ${output:jsonld-checker-api.url}
