name: jsonld-checker-api
app: jsonld-checker
component: express
org: gjgdserverless
repo: https://github.com/gjgd/jsonld-checker
license: MIT

inputs:
  src: ./
  domain: api.jsonld-checker.com
  env:
    TABLE_NAME: ${output:jsonld-checker-db.name}
    API_URL: ${output:jsonld-checker-api.url}
