name: jsonld-checker
component: website
repo: https://github.com/gjgd/jsonld-checker
license: MIT

inputs:
  domain: new.jsonld-checker.com
  src:
    src: ./src
    hook: npm run build
    dist: ./build
