name: CD

on:
  push:
    branches:
      - main
      - rename-main-branch

jobs:
  release-unstable:
    # Don't run on any commit that features [skip ci] in the commit message
    name: Publish unstable release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      # Use npm 7
      - run: npm install --global npm@latest

      - name: Install
        run: npm install

      - name: Setup npm profile
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          # Gives a clean failure prior to attempting a release if npm token is incorrect
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup git profile
        run: |
          git config user.name "GJGD"
          git config user.email $NPM_EMAIL
        env:
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}

      - run: cat .npmrc
      - run: git diff
      - name: Publish unstable version with lerna
        run: npm run publish:unstable
